version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: smart_entry_lot_container
    tty: true
    stdin_open: true
    volumes:
      - .:/smart_entry_lot
      - bundle_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      DATABASE_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444

volumes:
  db-data:
  bundle_data: