# 開発環境用（ローカルに保存）
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# テスト環境用
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# 本番環境用（AWS S3）
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_BUCKET'] %>